jQuery(document).keydown(function(event){if(event.keyCode==123){return!1}
else if(event.ctrlKey&&event.shiftKey&&event.keyCode==73){return!1}
else if(event.ctrlKey&&event.shiftKey&&event.keyCode==74){return!1}
else if((event.metaKey&&event.altKey)&&event.keyCode==73){return!1}});jQuery(document).ready(function(){jQuery('.scrolldown-arw').click(function(){var bannerheight=jQuery(window).height();jQuery('html,body').animate({scrollTop:bannerheight+"px"},'slow');return!1});document.oncontextmenu=document.body.oncontextmenu=function(){return!1};document.onkeydown=function(e){if(e.ctrlKey&&(e.keyCode===67||e.keyCode===86||e.keyCode===85||e.keyCode===117)){return!1}else{return!0}};var height=jQuery(window).height();var width=jQuery(window).width();var ismobile=(/android|webos|iphone|ipod|blackberry|iemobile|opera mini/i.test(navigator.userAgent.toLowerCase()));jQuery('.banner-section').css({'height':height+'px'});jQuery('.banner-section img').css({'height':height+'px'});jQuery(window).resize(function(){var height=jQuery(window).height();jQuery('.banner-section').css({'height':height+'px'});jQuery('.banner-section img').css({'height':height+'px'})});var header=document.querySelector(".headerblock");if(window.location.hash){header.classList.add("headroom--unpinned")}
var headroom=new Headroom(header,{tolerance:{down:10,up:20},offset:105});headroom.init();jQuery('.menu-icon').click(function(){jQuery('html, body').animate({scrollTop:jQuery('.menu-btn .full-width-menu').offset().top-100},1000);jQuery('.menu-btn').addClass('tran-open');setTimeout(function(){jQuery('body').addClass('position-fix');jQuery('body').removeClass('position-stat')},0)});jQuery('.serv-open').click(function(){jQuery('.menu-btn').addClass('tran-open');setTimeout(function(){jQuery('body').addClass('position-fix');jQuery('body').removeClass('position-stat')},0)});jQuery('.serv-open a').click(function(){jQuery(".serv-open").trigger("click");return!1});jQuery('.close-btn i').click(function(){jQuery('.menu-btn').addClass('tran-close');setTimeout(function(){jQuery('.menu-btn').removeClass('tran-close');jQuery('.menu-btn').removeClass('tran-open')},1200);setTimeout(function(){jQuery('body').removeClass('position-fix')},1200);setTimeout(function(){jQuery('body').addClass('position-stat')},1200)});var item_count=jQuery('.testimonial-slider li').length,loopStat=!1;if(item_count>1){loopStat=!0;if(item_count==1)loopStat=!1}
else{loopStat=!1}
var item_count=jQuery('.testimonial-slider li').length,loopStat=!1;if(item_count>1){loopStat=!0;if(item_count==1)loopStat=!1}
else{loopStat=!1}
jQuery('.testimonial-slider').owlCarousel({loop:loopStat,navRewind:loopStat,nav:!1,dots:!1,autoplay:!0,autoplayTimeout:12000,autoplayHoverPause:!0,animateIn:'fadeIn',animateOut:'fadeOut',margin:0,responsive:{0:{items:1,},480:{items:1},600:{items:1},1000:{items:1},}});jQuery('.has-submenu a').click(function(){jQuery(this).closest('li').find('.mobile-submenu').slideToggle()});if(jQuery('.move-to-top a').length){var scrollTrigger=100,backToTop=function(){var scrollTop=jQuery(window).scrollTop();if(scrollTop>scrollTrigger){jQuery('.move-to-top a').addClass('show')}
else{jQuery('.move-to-top a').removeClass('show')}};backToTop();jQuery(window).on('scroll',function(){backToTop()});jQuery('.move-to-top a').on('click',function(e){e.preventDefault();jQuery('html,body').animate({scrollTop:0},700)})}});jQuery(function(){var pgurl=window.location.href.substr(window.location.href.lastIndexOf("/")+1);jQuery(".main-menu li a").each(function(){if(jQuery(this).attr("href")==pgurl||jQuery(this).attr("href")=='')jQuery(this).addClass("active")});jQuery(".full-width-menu ul li a").each(function(){if(jQuery(this).attr("href")==pgurl||jQuery(this).attr("href")=='')jQuery(this).addClass("active")})})